name: Publish Artifacts to GitHub Releases

on:
  workflow_dispatch:
    inputs:
      release-name:
        description: "Release tag"
        required: true

permissions:
  contents: write

jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: "windows-python-dev-kit.yml"
          path: dist/

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release-name }}
          name: ${{ github.event.inputs.release-name }}
          draft: false
          prerelease: false
          files: dist/*.zip
