name: Publish Artifacts to GitHub Releases

on:
  workflow_dispatch:
    inputs:
      release-notes:
        description: "Release notes"
        required: false
        default: "Includes the latest build artifacts."

permissions:
  contents: write

jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: dawidd6/action-download-artifact@v12
        with:
          workflow: "windows-python-dev-kit.yml"
          path: dist/
          skip_unpack: true

      - name: Generate ISO8601 tag (git-safe)
        id: iso
        run: |
          echo "tag=$(date -u +'%Y-%m-%dT%H-%M-%SZ')" >> "$GITHUB_OUTPUT"

      - name: Create or update release
        uses: softprops/action-gh-release@v2.4.2
        with:
          tag_name: ${{ steps.iso.outputs.tag }}
          name: ${{ steps.iso.outputs.tag }}
          body: ${{ github.event.inputs.release-notes }}
          draft: false
          prerelease: false
          files: dist/*.zip
          overwrite_files: true
          make_latest: true
