name: Publish Artifacts to GitHub Releases

on:
  workflow_dispatch:
    inputs:
      release-name:
        description: "Release tag"
        required: true
      release-notes:
        description: "Release notes"
        required: false
        default: "Includes the latest build artifacts."

permissions:
  contents: write

jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: dawidd6/action-download-artifact@v12
        with:
          workflow: "windows-python-dev-kit.yml"
          path: dist/
          skip_unpack: true

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release-name }}
          name: ${{ github.event.inputs.release-name }}
          body: ${{ github.event.inputs.release-notes }}
          draft: false
          prerelease: false
          files: dist/*.zip
          overwrite_files: true
          make_latest: true
